# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FNBLine
                                 A QGIS plugin
 This plugin takes an area of interest and produces a PDF outlining overlapping layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-09
        copyright            : (C) 2019 by Evan Lavine 
        email                : evan.lavine@bc.gov.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FNBLine class from file FNBLine.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FN_BLine import FNBLine
    return FNBLine(iface)
